release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,16 +1,6 @@
 name: release
 on:
   workflow_dispatch:
-    inputs:
-      bump_type:
-        description: 'Bump type'
-        required: true
-        default: 'patch'
-        type: choice
-        options:
-          - major
-          - minor
-          - patch
 
 jobs:
   build_for_all_platforms:
@@ -22,19 +12,53 @@ jobs:
     runs-on: ${{ matrix.os }}
     outputs:
       tag: ${{ steps.tag.outputs.tag }}
+      bump_type: ${{ steps.bump_type.outputs.bump_type }}
+      last_tag: ${{ steps.last_tag.outputs.last_tag }}
     env:
       COMMIT_SHA: ${{ github.sha }}
       GEKO_LINUX_AUTOUPDATE_SOURCE: ${{ vars.GEKO_LINUX_AUTOUPDATE_SOURCE }}
       GEKO_MACOS_AUTOUPDATE_SOURCE: ${{ vars.GEKO_MACOS_AUTOUPDATE_SOURCE }}
-      BUMP_TYPE: ${{ github.event.inputs.bump_type }}
     steps:
       - uses: actions/checkout@v6.0.1
+        with:
+          fetch-depth: 0
+      - name: Fetch last tag
+        id: last_tag
+        run: |
+          git fetch --tags
 
+          LATEST_TAG=$(git tag -l "Geko@*" --sort=-version:refname | head -n 1)
+          if [ -z "$LATEST_TAG" ]; then
+            echo "Latest tag not found" >&2; exit 1;
+          fi
+          echo $LATEST_TAG
+          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
+          echo "last_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
+      - name: Calculate new version
+        id: bump_type
+        run: |
+          LATEST_TAG="${{ env.LATEST_TAG }}"
+
+          all_messages=$(git log "$LATEST_TAG"..HEAD --format=%B | grep -E "\[(patch|minor|major)\] (feat|fix|refactor): .*")
+          echo $all_messages
+
+          NEW_BUMP_TYPE=""
+          if [[ "$all_messages" == *"[major]"* ]]; then
+          NEW_BUMP_TYPE="major"
+          elif [[ "$all_messages" == *"[minor]"* ]]; then
+          NEW_BUMP_TYPE="minor"
+          else
+          NEW_BUMP_TYPE="patch"
+          fi
+          echo "bump_type is $NEW_BUMP_TYPE"
+          echo "NEW_BUMP_TYPE=$NEW_BUMP_TYPE" >> $GITHUB_ENV
+          echo "bump_type=$NEW_BUMP_TYPE" >> $GITHUB_OUTPUT
       - name: Build
         id: build
         run: |
+          NEW_BUMP_TYPE="${{ env.NEW_BUMP_TYPE }}"
           export CI_COMMIT_SHORT_SHA=${COMMIT_SHA:0:8}
-          scripts/linux/build.sh -n Geko -b ${BUMP_TYPE:-"minor"}
+          scripts/linux/build.sh -n Geko -b ${BUMP_TYPE:-"$NEW_BUMP_TYPE"}
           echo "arch=$(uname -m)" >> $GITHUB_OUTPUT
 
       - name: Remember version
@@ -64,33 +88,71 @@ jobs:
       pull-requests: write
     env:
       TAG: ${{ needs.build_for_all_platforms.outputs.tag }}
-      BUMP_TYPE: ${{ github.event.inputs.bump_type }}
+      COMMIT_SHA: ${{ github.sha }}
+      BUMP_TYPE: ${{ needs.build_for_all_platforms.outputs.bump_type }}
+      LATEST_TAG: ${{ needs.build_for_all_platforms.outputs.last_tag }}
     steps:
+      - uses: actions/create-github-app-token@v2
+        id: app-token
+        with:
+          app-id: ${{ secrets.APP_ID }}
+          private-key: ${{ secrets.APP_PRIVATE_KEY }}
       - uses: actions/checkout@v6.0.1
-
+        with:
+          fetch-depth: 0
       - name: Download artifacts
         uses: actions/download-artifact@v7
         with:
           path: build_artifacts
           merge-multiple: true
-
-      - name: Bump version
+      - name: Get GitHub App User ID
+        id: get-user-id
+        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
+        env:
+          GH_TOKEN: ${{ steps.app-token.outputs.token }}
+      - name: Setup committer
         run: |
+          git config user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
+          git config user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
+      - name: Bump version and update changelog
+        run: |
+          git fetch --tags
           NEW_VERSION=$(scripts/linux/new_version_number.sh -n Geko -b $BUMP_TYPE)
-          BASE=$(git branch --show-current)
-          branch="automation/bump_version_geko"
-          git branch -D $branch || true
-          git checkout -b $branch
+
+          ALL_MESSAGES=$(git log "$LATEST_TAG"..HEAD --format=%B | grep -E "\[(patch|minor|major)\] (feat|fix|refactor): .*")
+          echo "$ALL_MESSAGES"
+          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
+          echo "$ALL_MESSAGES" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+
+          FILE="Geko_Changelog.md"
+          TEMP_FILE="temp.md"
+          NEW_CONTENT="## Geko $NEW_VERSION
+          $ALL_MESSAGES
+          "
+          if grep -q "Geko $NEW_VERSION" "$FILE"; then
+            echo "The file '$FILE' contains new changes"
+          else
+            echo "$NEW_CONTENT" > "$TEMP_FILE"
+            cat "$FILE" >> "$TEMP_FILE"
+            mv "$TEMP_FILE" "$FILE"
+          fi
+          if git ls-remote --exit-code --tags origin "$TAG"; then
+            echo "Tag $TAG found."
+          else
+            echo "Tag $TAG not found. Creating..."
+            git tag $TAG
+            git push origin $TAG
+          fi
           git add Sources/GekoSupport/Constants.swift
+          git add $FILE
           if ! git commit -m "Update app version to $NEW_VERSION"; then
               echo "Nothing to commit. Sources/GekoSupport/Constants.swift has already correct version $NEW_VERSION"
               exit 0
           fi
-          git push -u origin "$branch"
-          export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
-          gh pr create --fill
-          gh pr merge --admin --squash --delete-branch
-          git checkout "$BASE"
-          git pull
-          COMMIT_SHA=$(git rev-parse HEAD)
-          gh release create $TAG -d --generate-notes --target $COMMIT_SHA build_artifacts/*
+          git push
+      - name: Create draft release
+        run: |
+          gh release create $TAG -d --title $TAG --notes "${{ env.CHANGELOG }}" --target $COMMIT_SHA build_artifacts/*
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
diff --git a/.github/workflows/release_desktop.yml b/.github/workflows/release_desktop.yml
--- a/.github/workflows/release_desktop.yml
+++ b/.github/workflows/release_desktop.yml
@@ -1,11 +1,6 @@
 name: Release GekoDesktop
 on:
   workflow_dispatch:
-    inputs:
-      version:
-        description: "Version"
-        required: true
-        type: string
 
 jobs:
   build_desktop:
@@ -15,7 +10,6 @@ jobs:
       contents: write
     env:
       BUILD_DIR: "GekoDesktop/build_output"
-      VERSION: ${{ github.event.inputs.version }}
       VERSION_FILE: GekoDesktop/GekoDesktop/Sources/Support/Constants/Constants.swift
     steps:
       - uses: actions/create-github-app-token@v2
@@ -26,7 +20,54 @@ jobs:
 
       - uses: actions/checkout@v6.0.1
         with:
+          fetch-depth: 0
           token: ${{ steps.app-token.outputs.token }}
+
+      - name: Fetch last tag
+        run: |
+          git fetch --tags
+
+          LATEST_TAG=$(git tag -l "Desktop@*" --sort=-version:refname | head -n 1)
+          if [ -z "$LATEST_TAG" ]; then
+            echo "Latest tag not found" >&2; exit 1;
+          fi
+          echo $LATEST_TAG
+          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
+      - name: Calculate new version
+        id: bump_type
+        run: |
+          LATEST_TAG="${{ env.LATEST_TAG }}"
+
+          LATEST_VERSION=$(echo "$LATEST_TAG" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
+          if [ -n "$LATEST_VERSION" ]; then
+            LATEST_VERSION="${LATEST_VERSION}"
+          else
+            echo "Failed to extract version from tag: $LATEST_TAG" >&2; exit 1;
+          fi
+
+          all_messages=$(git log "$LATEST_TAG"..HEAD --format=%B | grep -E "desktop \[(patch|minor|major)\] (feat|fix|refactor): .*")
+          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
+          echo "$all_messages" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+
+          echo $all_messages
+          chmod +x ./scripts/utils/incr_semver.sh
+
+          NEW_BUMP_TYPE=""
+          NEW_VERSION=""
+          if [[ "$all_messages" == *"[major]"* ]]; then
+          NEW_BUMP_TYPE="major"
+          NEW_VERSION=$(./scripts/utils/incr_semver.sh "$LATEST_VERSION" major)
+          elif [[ "$all_messages" == *"[minor]"* ]]; then
+          NEW_BUMP_TYPE="minor"
+          NEW_VERSION=$(./scripts/utils/incr_semver.sh "$LATEST_VERSION" minor)
+          else
+          NEW_BUMP_TYPE="patch"
+          NEW_VERSION=$(./scripts/utils/incr_semver.sh "$LATEST_VERSION" patch)
+          fi
+          echo "bump_type is $NEW_BUMP_TYPE"
+          echo "NEW_BUMP_TYPE=$NEW_BUMP_TYPE" >> $GITHUB_ENV
+          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
 
       - name: Get GitHub App User ID
         id: get-user-id
@@ -44,7 +85,8 @@ jobs:
 
       - name: Build Release Binary
         run: |
-          sed -i '' -E 's|let appVersion = "[0-9.]*"|let appVersion = \"'"$VERSION"'\"|' $VERSION_FILE
+          NEW_VERSION="${{ env.NEW_VERSION }}"
+          sed -i '' -E 's|let appVersion = "[0-9.]*"|let appVersion = \"'"$NEW_VERSION"'\"|' $VERSION_FILE
 
           (cd GekoDesktop && xcodegen generate)
           fastlane gym \
@@ -59,17 +101,47 @@ jobs:
 
           (cd $BUILD_DIR && zip -r ../../GekoDesktop.app.zip GekoDesktop.app)
 
-      - name: Commit version change
+      - name: Commit changes
         id: commit_bump_version
         run: |
+          NEW_VERSION="${{ env.NEW_VERSION }}"
+          ALL_MESSAGES="${{ env.CHANGELOG }}"
+          FILE="Desktop_Changelog.md"
+          TEMP_FILE="temp.md"
+          NEW_CONTENT="## Desktop $NEW_VERSION
+          $ALL_MESSAGES
+          "
+          if grep -q "Desktop $NEW_VERSION" "$FILE"; then
+            echo "The file '$FILE' contains new changes"
+          else
+            echo "$NEW_CONTENT" > "$TEMP_FILE"
+            cat "$FILE" >> "$TEMP_FILE"
+            mv "$TEMP_FILE" "$FILE"
+          fi
+    
           git add $VERSION_FILE
-          git commit -m "Bump GekoDesktop app version to $VERSION"
+          git add $FILE
+          git commit -m "Bump GekoDesktop app version to $NEW_VERSION"
           git push
+
+      - name: Add tag
+        run: |
+          NEW_VERSION="${{ env.NEW_VERSION }}"
+          NEW_TAG="Desktop@$NEW_VERSION"
+          if git ls-remote --exit-code --tags origin "$NEW_TAG"; then
+            echo "Tag $NEW_TAG found."
+          else
+            echo "Tag $NEW_TAG not found. Creating..."
+            git tag $NEW_TAG
+            git push origin $NEW_TAG
+          fi
 
       - name: Create draft release
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           BASE: ${{ steps.commit_bump_version.outputs.base }}
         run: |
+          NEW_VERSION="${{ env.NEW_VERSION }}"
+          NEW_TAG="Desktop@$NEW_VERSION"
           COMMIT_SHA=$(git rev-parse HEAD)
-          gh release create "GekoDesktop@$VERSION" -d --generate-notes --target $COMMIT_SHA GekoDesktop.app.zip
+          gh release create $NEW_TAG -d --title $NEW_TAG --notes "${{ env.CHANGELOG }}" --target $COMMIT_SHA GekoDesktop.app.zip
